domain: jacobhodgins.github.io
url: https://jacobhodgins.github.io
baseurl: /hodginsjacob/
name: Jacob Hodgins
markdown: kramdown
permalink: /projects/:year/:month/:day/:title
remote_theme: al-folio
paginate: 5
paginate_path: "/blog/page:num/"
